version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - app-network

  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: myapp
      DB_USER: user
      DB_PASSWORD: password
    networks:
      - app-network

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      # - CHOKIDAR_USEPOLLING=true คือ hot reloading code เปลี่ยน หน้าเว็บเปลี่ยนตามเลย
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./pg-admin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  frontend:
  backend:
  db-data:
  pg-admin-data: